/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f3f4",
        "primary-fixed-dim": "#474646",
        "on-surface": "#1a1c1c",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#e5e2e1",
        "primary": "#000000",
        "on-tertiary": "#d8e2ff",
        "on-surface-variant": "#474747",
        "surface-container": "#eeeeee",
        "inverse-on-surface": "#f0f1f1",
        "on-background": "#1a1c1c",
        "on-tertiary-fixed": "#ffffff",
        "tertiary-container": "#2771df",
        "on-tertiary-container": "#ffffff",
        "surface-dim": "#dadada",
        "secondary-container": "#d5d4d4",
        "on-secondary-fixed-variant": "#3a3c3c",
        "error-container": "#ffdad6",
        "secondary": "#5e5e5f",
        "surface": "#f9f9f9",
        "primary-container": "#3c3b3b",
        "tertiary-fixed-dim": "#004494",
        "inverse-surface": "#2f3131",
        "tertiary": "#00397e",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#d8e2ff",
        "surface-bright": "#f9f9f9",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#c7c6c6",
        "surface-variant": "#e2e2e2",
        "surface-container-high": "#e8e8e8",
        "surface-tint": "#5f5e5e",
        "primary-fixed": "#5f5e5e",
        "on-secondary-fixed": "#1a1c1c",
        "on-error-container": "#410002",
        "outline-variant": "#c6c6c6",
        "surface-container-highest": "#e2e2e2",
        "on-primary-container": "#ffffff",
        "background": "#f9f9f9",
        "outline": "#777777",
        "secondary-fixed-dim": "#ababab",
        "on-primary": "#e5e2e1",
        "inverse-primary": "#c9c6c5",
        "on-secondary-container": "#1a1c1c",
        "on-primary-fixed": "#ffffff",
        "tertiary-fixed": "#005ac1",
        "surface-container-lowest": "#ffffff",

        // Keep old fallbacks temporarily to prevent crashes during migration
        bg: {
          primary: 'var(--color-surface-lowest)',
          secondary: 'var(--color-surface-low)',
          card: 'var(--color-surface-lowest)',
          elevated: 'var(--color-surface-low)',
        },
        border: {
          default: 'var(--color-outline-variant)',
          active: 'var(--color-primary)',
        },
        text: {
          primary: 'var(--color-on-surface)',
          secondary: 'var(--color-secondary)',
          muted: 'var(--color-outline)',
        },
        risk: {
          low: '#16A34A',
          moderate: '#EAB308',
          high: '#ba1a1a',
          critical: '#ba1a1a',
        },
        accent: {
          blue: '#2771df',
        }
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Plus Jakarta Sans"],
        label: ["Plus Jakarta Sans"],
        mono: ['"JetBrains Mono"', 'monospace'],
        heading: ['"Plus Jakarta Sans"', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
